name = "DataBags"
uuid = "497ad153-c143-42a2-80c7-87bdfcf8382a"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.0, 1.1, 1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[targets]
test = ["Test", "Dates"]
